name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ vars.VPS_IP }} >> ~/.ssh/known_hosts

    - name: Rsync files to VPS
      run: |
        rsync -avz --delete ./ ubuntu@${{ vars.VPS_IP }}:${{ vars.PORTFOLIO_PATH }}

    - name: Reload Caddy
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@${{ vars.VPS_IP }} "sudo systemctl reload caddy"